name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - run: bundle exec rubocop
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['4.0', '3.4', '3.3', '3.2']
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rspec
